export const queryKeys = {
  state: ['state'] as const,
  config: ['config'] as const,
  githubStatus: ['github', 'status'] as const,
  githubRepos: ['github', 'repos'] as const,
  githubBranches: (repo: string) => ['github', 'branches', repo] as const,
  githubDirs: (repo: string, branch: string, path = '') =>
    ['github', 'dirs', repo, branch, path] as const,
  githubSSHKey: ['github', 'ssh-key'] as const,
  groups: ['groups'] as const,
  services: (group: string) => ['services', group] as const,
  groupStats: (group: string) => ['stats', group] as const,
  service: (group: string, slug: string) => ['service', group, slug] as const,
  serviceEnv: (group: string, slug: string) => ['service', group, slug, 'env'] as const,
  serviceLogs: (group: string, slug: string) => ['service', group, slug, 'logs'] as const,
  deployments: (group: string, slug: string) => ['deployments', group, slug] as const,
  deployLogs: (group: string, slug: string, id: string) =>
    ['deployments', group, slug, id, 'logs'] as const,
  ports: ['ports'] as const,
  manage: ['manage'] as const,
  engine: ['engine'] as const,
  files: (path: string) => ['files', path] as const,
  filesPreview: (path: string) => ['files', 'preview', path] as const,
  activity: ['activity'] as const,
}
